INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (N'3586e205-1f4a-4af4-9fa1-77cb22999aed', N'viewer', N'viewer', N'0b6df70d-7768-4f92-8942-198eab988a3b')
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (N'3fe79d55-69f6-4b8d-83e3-c2f1babb4248', N'author', N'author', N'db45a77c-ee57-440c-866a-16c208e8be6f')
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'0af69d8b-e7a8-41a4-a026-eb02cdc1763d', N'jackson@gmail.com', N'JACKSON@GMAIL.COM', N'jackson@gmail.com', N'JACKSON@GMAIL.COM', 1, N'AQAAAAEAACcQAAAAECAdH7Or9mprQtAk0vr/TgmxwvRd2KLbzvxFwsq5e20daqpK8ga1aKyY4K76GcVLyQ==', N'MWQAASWU63V7WPDPS4YMA5236X5VKIYT', N'2f75a28c-fbcb-436b-bae1-ed7b17b124c4', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'49841308-ae80-49f8-acb7-d85f3c6a93da', N'frank@gmail.com', N'FRANK@GMAIL.COM', N'frank@gmail.com', N'FRANK@GMAIL.COM', 1, N'AQAAAAEAACcQAAAAEHV8yQsY/DPrcrdD+NB9gVerWx52WxxfW1nxr0OaPqb+sfZr4BfvWgG/oRL0LcLUDA==', N'FXOKCXKITGDHHTVMTET7EHFQ64LZRNXT', N'ce29f7f7-52fd-4d1a-b030-baf2d7a0658d', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'b7f80a98-7dc7-48e5-afc3-7d3d9c71681f', N'lily@gmail.com', N'LILY@GMAIL.COM', N'lily@gmail.com', N'LILY@GMAIL.COM', 1, N'AQAAAAEAACcQAAAAEIYAkfQ2b8Nj61ixN9ppOySRcJJcW6ClENQtUpMY8jEDpywKicMlEIhMu8gh9cV9cA==', N'DZ7ES32KRYNPU6CROVRPSFPPXWRDCQ7S', N'a2ee0b74-81b1-427f-afd9-c6c07431ad7f', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUserRoles] ([UserId], [RoleId]) VALUES (N'b7f80a98-7dc7-48e5-afc3-7d3d9c71681f', N'3586e205-1f4a-4af4-9fa1-77cb22999aed')
INSERT INTO [dbo].[AspNetUserRoles] ([UserId], [RoleId]) VALUES (N'0af69d8b-e7a8-41a4-a026-eb02cdc1763d', N'3fe79d55-69f6-4b8d-83e3-c2f1babb4248')
INSERT INTO [dbo].[AspNetUserRoles] ([UserId], [RoleId]) VALUES (N'49841308-ae80-49f8-acb7-d85f3c6a93da', N'3fe79d55-69f6-4b8d-83e3-c2f1babb4248')
SET IDENTITY_INSERT [dbo].[Author] ON
INSERT INTO [dbo].[Author] ([Id], [Name], [Email]) VALUES (1, N'Jackson Kelly', N'jackson@gmail.com')
INSERT INTO [dbo].[Author] ([Id], [Name], [Email]) VALUES (2, N'Frank Newton', N'frank@gmail.com')
SET IDENTITY_INSERT [dbo].[Author] OFF
SET IDENTITY_INSERT [dbo].[Viewer] ON
INSERT INTO [dbo].[Viewer] ([Id], [Name], [Email]) VALUES (1, N'Lilly Simons', N'lily@gmail.com')
SET IDENTITY_INSERT [dbo].[Viewer] OFF

SET IDENTITY_INSERT [dbo].[WikiPage] ON
INSERT INTO [dbo].[WikiPage] ([Id], [Title], [Content], [LastModifed], [AuthorId]) VALUES (1, N'How Often Should You Clean Your Humidifier?', N'It''s the end of a long day, and you''ve grudgingly brushed, flossed, washed your face and performed other tedious tasks when you''d much rather just fall right in bed. Suddenly, the humidifier looms large. The tank is half full, so why not just save yourself an extra chore and re-use last night''s water? Then there''s the fact that a different president was in office the last time you performed a full clean of the small appliance, but surely, the water running through keeps it clean enough, right? As much as we hate to be Humidifier Henrietta, both of these common mistakes are actually risky for your overall health.  So why''s that? First off, you need to know what a humidifier is in the first place. There are a bunch of different types (warm-mist, cool-mist, ultrasonic), but they all shoot for the same goals of restoring moisture to the atmosphere to help people breathe better, relieving dry skin, stopping static electricity and even protecting your wooden furniture. Too little humidity is very common in the winter once the indoor heater gets cranked up, drying out the air and sometimes resulting in chapped lips, bloody noses and breathing issues. A warm mist humidifier can still provide heat without drying out the air in your room.', N'2020-04-22 09:00:00', 1)
INSERT INTO [dbo].[WikiPage] ([Id], [Title], [Content], [LastModifed], [AuthorId]) VALUES (2, N'Chimerism: You Can Be Your Own Twin', N'Taylor Muhl is a beautiful woman and a talented singer. She also happens to be a chimera, someone who carries two distinct sets of DNA, each with the genetic code to make a completely separate person. KEITH BERSON When Taylor Muhl, a California-based singer, asked a doctor to investigate the birthmark that demarcated the left side of her torso, she wondered what role the ruddy patch might play — if any — in a series of seemingly disparate health conditions she had experienced most of her life.  “Everything on the left side of my body is slightly larger than the right side,” Muhl says. “I have a double tooth in the left side of my mouth and many sensitivities and allergies to foods, medications, supplements, jewelry and insect bites.”', N'2020-05-05 22:45:00', 2)
SET IDENTITY_INSERT [dbo].[WikiPage] OFF


